services:
  app:
    env_file:
      - path: ../../.env
        required: false
    depends_on:
      - web-db
      - web-test-db

  web-db:
    env_file:
      - path: ../../.env
        required: false

  web-test-db:
    env_file:
      - path: ../../.env
        required: false
